# git-cliff ~ default configuration file
# https://git-cliff.org/docs/configuration
#
# Lines starting with "#" are comments.
# Configuration options are organized into tables and keys.
# See documentation for more information on available options.

[changelog]
# changelog header
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
"""
# template for the changelog body
# https://keats.github.io/tera/docs/#introduction
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{%- set excluded_users = ["github-actions[bot]", "dependabot[bot]", "renovate[bot]"] -%}

{% macro print_commit(commit) -%}
    - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
        {% if commit.breaking %}[**breaking**] {% endif %}\
        {{ commit.message | upper_first }} - \
        ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))\
{% endmacro -%}

{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}]({{ self::remote_url() }}/compare/{{ previous.version }}..{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {% else %}\
        ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
    {% endif %}\
{% else %}\
    ## [unreleased]
{% endif %}\

{%- for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {%- for commit in commits | filter(attribute="scope") | sort(attribute="scope") %}
        {{ self::print_commit(commit=commit) }}
    {%- endfor %}
    {%- for commit in commits %}
        {%- if not commit.scope %}
            {{ self::print_commit(commit=commit) }}
        {%- endif %}
    {%- endfor -%}
{%- endfor -%}

{%- set valid_contributors = [] -%}
{%- for c in github.contributors | filter(attribute="is_first_time", value=true) %}
  {%- if c.username and c.username not in excluded_users and c.username not in valid_contributors %}
    {%- set_global valid_contributors = valid_contributors | concat(with=c.username) %}
  {%- endif %}
{%- endfor %}

{%- if valid_contributors | length > 0 %}
## New Contributors ❤️
  {%- for username in valid_contributors %}
* @{{ username }} made their first contribution
  {%- endfor %}
{%- endif %}
"""

trim = true
footer = """
"""
postprocessors = [
    { pattern = '<REPO>', replace = "https://github.com/szinn/hex-play" }, # replace repository URL
]

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
filter_commits = true
commit_preprocessors = [
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))" }, # replace issue numbers
    { pattern = '.*\[skip ci\].*', replace = "" },
    { pattern = '.*\[ci skip\].*', replace = "" },
]
commit_parsers = [
    { message = "^fix!?\\(deps\\)", skip = true },
    { message = "^chore!?\\(deps\\)", skip = true },
    { message = "^ci!?\\(renovate\\)", skip = true },
    { message = "^ignore", skip = true },
    { message = "^feat", group = "<!-- 0 -->Features" },
    { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
    { message = "^doc", group = "<!-- 3 -->Documentation" },
    { message = "^perf", group = "<!-- 4 -->Performance" },
    { message = "^refactor", group = "<!-- 2 -->Refactor" },
    { message = "^style", group = "<!-- 5 -->Stying" },
    { message = "^test", group = "<!-- 6 -->Testing" },
    { message = "^chore\\(release\\): prepare for", skip = true },
    { message = "^feat!?\\(deps\\)", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^chore|^ci", group = "<!-- 7 -->Miscellaneous Tasks" },
    { message = "^ci", group = "<!-- 7 -->Miscellaneous Tasks" },
    { body = ".*security", group = "<!-- 8 -->Security" },
    { message = "^revert", group = "<!-- 9 -->Revert" },
]
protect_breaking_commits = false
tag_pattern = "v?[0-9]+\\.[0-9]+\\.[0-9]+.*"
skip_tags = "alpha|beta|rc"
ignore_tags = "prerelease|beta|alpha"
topo_order = false
sort_commits = "newest"
